---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment-50001
spec:
  selector:
    matchLabels:
      app: csb
      department: batch6
  replicas: 3
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: csb
        department: batch6
    spec:
      containers:
      - name: hello
        image: "gcr.io/google-samples/hello-app:2.0"
        env:
        - name: "PORT"
          value: "50001"
---
apiVersion: v1
kind: Service
metadata:
  name: my-lb-service
spec:
  type: LoadBalancer
  selector:
    app: csb
    department: batch6
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 50001
